echo lab_10\test_output.txt
TextVM.exe lab_10\test_output.txt
echo lab_11\test_output.txt
TextVM.exe lab_11\test_output.txt
echo lab_12\ex1\test_output-1.txt
TextVM.exe lab_12\ex1\test_output-1.txt
echo lab_12\ex2\test_output-2.txt
TextVM.exe lab_12\ex2\test_output-2.txt
echo lab_12\ex3\test-extra-output.txt
TextVM.exe lab_12\ex3\test-extra-output.txt
echo lab_12/extra_features/multiple_definitions/test-output.txt
TextVM.exe lab_12/extra_features/multiple_definitions/test-output.txt
echo lab_12/extra_features/multi_read_writes/test-output.txt
TextVM.exe lab_12/extra_features/multi_read_writes/test-output.txt
echo lab_12/extra_features/type_promotion/test-output.txt
TextVM.exe lab_12/extra_features/type_promotion/test-output.txt
echo lab_12/extra_features/structs/test-output.txt
TextVM.exe lab_12/extra_features/structs/test-output.txt
echo lab_12/extra_features/type_defs/test-output.txt
TextVM.exe lab_12/extra_features/type_defs/test-output.txt
echo lab_09\test-low-level-mapl-1.txt
TextVM.exe lab_09\test-low-level-mapl-1.txt
echo lab_09\test-low-level-mapl-2.txt
TextVM.exe lab_09\test-low-level-mapl-2.txt
